--- 
title: "EZCancerTarget Documentation"
author: "David Dora MD, PhD; Timea Dora MS; Gabor Szegvari MS; Csongor Gerdán BS; Zoltan Lohinai MD, PhD"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [ data.sources.bib, packages.bib ]
nocite: |
  @*
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "An Open-access Drug Repurposing and Data-mining Platform to Enhance Target Validation and Optimize International Research Efforts against Highly Progressive Cancers"
---

# Introduction

_EZCancerTarget_ provides detailed biological information on the selected set of
target molecules using open-access databases, such as _UniProt_, _GeneCards_,
_Gene Ontology_ and _STRING_ - @uniprot2020; @genecards2021;
@ashburner_gene_2000; @the_gene_ontology_consortium_gene_2021; @szklarczyk_string_2021.
This way, the user receives a concise summary on
the biological relevance of every target, that is explicitly important for
researchers who are not experts in molecular biology.

## How to Cite EZCancerTarget

David Dora, Timea Dora, Gabor Szegvari, Csongor Gerdán, Zoltan Lohinai 2022.
EZCancerTarget: an open-access drug repurposing and data-collection tool to enhance target validation and optimize international research efforts against highly progressive cancers. _BioData Mining_ __15__, 25 (2022). https://doi.org/10.1186/s13040-022-00307-9

## Running with no installation

### Input Google Spreadsheet

[EZCancerTarget - Target INPUT table](https://docs.google.com/spreadsheets/d/1oQtWxPJASB-WfwqnyBJr3woXmv03bu3iSzIrKyK2-t8/) - the easiest way to provide input dataset to ```EZCancerTarget``` workflow and start it on GitHub.

Its access requires

* a Google account,
* an editor permission,
* cooperations with other users to avoid unintended changes of initial dataset.

### Result page and workflow status check

* Result of recent targets: [index.target.with.data.html](https://cycle20.github.io/EZCancerTarget/index.target.with.data.html)
* [Baseline version of result page](https://cycle20.github.io/EZCancerTarget/baseline/index.target.with.data.html)
* [Workflow results](https://github.com/cycle20/EZCancerTarget/actions/workflows/clue.yml) - list of each workflow run on GitHub.


