#
# clue.yml: simplified workflow
#

name: clue
env:
  ARTIFACT_01: clue.R.tgz
  ARTIFACT_02: dataPatch.R.tgz
  ARTIFACT_03: renderWebPage.R.tgz
  UNIPROT_CACHE_DIR: G.D.CACHE

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # JOB: CLUE
  clue:
    name: "Download perturbagens from clue.io (R/clue.R)"
    runs-on: ubuntu-latest

    steps:


# clue ########################################################


      - uses: actions/checkout@v2

      #
      # Dependencies
      #
      - name: "Dependencies: R pkgs from added PPA and CRAN"
        run: sudo bash src/gh_action__setup_and_install.bash

      # Exec clue.R
      - name: R/clue.R
        run: Rscript R/clue.R
        env:
          CLUE_USER_KEY: ${{ secrets.CLUE_USER_KEY }}
          SERVICE_TOKEN_JSON: ${{ secrets.CLUE_GS4_SERVICE_TOKEN_JSON }}
          TARGET_LIST_ID: ${{ secrets.TARGET_LIST_ID }}

      # Wrap OUTPUT directory
      - name: Create archive file for "caching"
        run: bash src/wrap_directory.bash "${{ env.ARTIFACT_01 }}" OUTPUT

      # Caching
      - name: Upload result artifact as a cache custom cache solution
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "${{ env.ARTIFACT_01 }}"
          path: "${{ env.ARTIFACT_01 }}"
          retention-days: 1

      - name: Checksum of artifact
        run: md5sum "${{ env.ARTIFACT_01 }}"


# dataPatch ###################################################


      # UniProt "cache" (it is needed for correct subcellular images)
      - name: "Drive task: download external UniProt cache stuff"
        run: |
          echo "Download cache stuff..."
          bash src/google_download.bash "${{ secrets.UNIPROT_PRE_CACHED }}" u.tgz
          echo "md5sum of cache file"
          md5sum u.tgz

      - name: tarball verbosed extraction of UniProt cache stuffs into ${{ env.UNIPROT_CACHE_DIR }}
        run: |
          mkdir -p "${{ env.UNIPROT_CACHE_DIR }}"
          tar --directory="${{ env.UNIPROT_CACHE_DIR }}" -xzf u.tgz

      - name: Merge UniProt cache into restored OUTPUT directory
        run: |
          UNI_CACHE="${{ env.UNIPROT_CACHE_DIR }}"
          GH_CACHE="OUTPUT/DATAPATH_CACHE"
          bash src/gh_action__merge_caches.bash "$UNI_CACHE" "$GH_CACHE"


      # Exec dataPatch.R
      # TODO: this can be a long process: downloads in parallel jobs is a potential improvement
      - name: R/dataPatch.R
        run: Rscript R/dataPatch.R

      # Wrap OUTPUT into tar package
      - name: Prepare archive file for upload
        run: |
          md5sum OUTPUT/clue_patched.rds
          bash src/wrap_directory.bash "${{ env.ARTIFACT_02 }}" OUTPUT
          md5sum "${{ env.ARTIFACT_02 }}"

      # Caching
      - name: Upload result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "${{ env.ARTIFACT_02 }}"
          path: "${{ env.ARTIFACT_02 }}"

      - name: Checksum of artifact
        run: md5sum "${{ env.ARTIFACT_02 }}"


# render  #####################################################


      - name: Exec page rendering (renderWebPage.R)
        run: |
          Rscript R/renderWebPage.R
          ls -lt OUTPUT/*.html
          tree -d ..

      - name: "Wrap pages into '${{ env.ARTIFACT_03 }}'"
        run: |
          tar --directory=OUTPUT -cvzf "${{ env.ARTIFACT_03 }}" \
            index.target.with.data.html index.target.no_data.html

      - name: "Upload artifact '${{ env.ARTIFACT_03 }}'"
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "${{ env.ARTIFACT_03 }}"
          path: "${{ env.ARTIFACT_03 }}"
          retention-days: 5

      - name: Checksum of artifact
        run: md5sum "${{ env.ARTIFACT_03 }}"


# deploy ######################################################


      - name: Save OUTPUT directory
        run: mv OUTPUT ..

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Restore OUTPUT directory
        run: mv .. OUTPUT

      - name: gh-pages "deploy"
        run: |
          git config  --local user.email "46718432+cycle20@users.noreply.github.com"
          git config  --local user.name cycle20

          md5sum OUTPUT/clue_patched.rds

          mv OUTPUT/index.target.with.data.html . || {
            tree -d ..
            ls -lt
            exit 1
          }
          git add index.target.with.data.html
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          git commit -F <(\
            printf "Pushed by workflow: %s, run number: %d\n\n$RUN_URL" \
              "$GITHUB_WORKFLOW" \
              "$GITHUB_RUN_NUMBER" \
          )

          git push "https://${{ secrets.GH_PAGES_PAT }}@github.com/cycle20/scancer.git" \
            gh-pages:gh-pages
          git log -1
          git status
