name: cocomo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ sandbox ]
  workflow_dispatch:

jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: A job to count the lines of code.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the lines of code.
        id: scc
        run: |
          sudo snap install scc
          find  R src web \
            -name "*.bash" \
            -o -name "*.R" \
            -o -name "*.md" \
            -o -name "*.html" \
            | xargs scc
