name: cocomo
on:

  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: COCOMO by scc
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the lines of code.
        id: scc
        run: |
          sudo snap install scc
          find R src web .github/workflows \
            -name "*.bash" \
            -o -name "*.R" \
            -o -name "*.md" \
            -o -name "*.html" \
            -o -name "*.yml" \
            | xargs scc
