#
# deployPages.yml: workflow of "deployPages" job
#

name: deployPages
env:
  ARTIFACT_01: clue.R.tgz
  ARTIFACT_02: dataPatch.R.tgz
  ARTIFACT_03: renderWebPage.R.tgz
  UNIPROT_CACHE_DIR: G.D.CACHE

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:

  deployPages:
    name: Commit new pages from artifact of render job
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Environment
        run: env | sort -u

      - name: get artifact "${{ env.ARTIFACT_03 }}"
        run: |
          tree -d
          # get the script file
          curl -o get_artifact.bash  https://raw.githubusercontent.com/cycle20/scancer/main/src/get_artifact.bash

          bash get_artifact.bash "${{ secrets.GITHUB_TOKEN }}" "${{ env.ARTIFACT_03 }}"
          # drop the script file (from the index as well)
          rm get_artifact.bash
          tree -d

      - name: gh-pages "deploy"
        run: |
          git config  --local user.email "46718432+cycle20@users.noreply.github.com"
          git config  --local user.name cycle20

          mv PREV_RESULT/index.target.with.data.html .
          git add index.target.with.data.html
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          git commit -F <(\
            printf "Pushed by workflow: %s, run number: %d\n\n$RUN_URL" \
              "$GITHUB_WORKFLOW" \
              "$GITHUB_RUN_NUMBER" \
          )

          git push "https://${{ secrets.GH_PAGES_PAT }}@github.com/cycle20/scancer.git" \
            gh-pages:gh-pages
          git log -1
          git status
