# This is a basic workflow to help you get started with Actions

# NOTE:
# Further readings: https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+
#                   https://github.com/r-lib/actions
#                   https://pkgs.org/download/r-base-core
#
# Cache and "share": https://github.com/actions/cache
#                    https://rstudio.github.io/renv/articles/renv.html#cache
#                    https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
#                    https://thomasadventure.blog/posts/install-r-packages/

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ target ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup and install"
  setup_and_install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #
      # Install R pkgs
      #
      - name: Add cran2deb4ubuntu 4.0 PPA
        run: sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
      - name: apt-get update & install aptitude
        run: |
          sudo apt-get update
          sudo apt-get install aptitude -y
      - name: apt-get upgrade
        run: sudo apt-get upgrade

      #sudo apt-get install --fix-broken --assume-yes r-base-core r-cran-dplyr r-cran-httr r-cran-jsonlite r-cran-readr r-cran-stringr r-cran-xml2 r-cran-whisker

      # rvest dependencies by binaries
      - name: rvest deps
        run: sudo aptitude install -f -y r-cran-dplyr r-cran-httr r-cran-jsonlite r-cran-selectr r-cran-xml2

      # Install r-vest
      - name: rvest packge install
        run: sudo /usr/bin/R -e 'install.packages("rvest")'

      # R site-library after install
      - name: R site-library
        run: ls -lt /usr/lib/R/site-library/
        
      # R library after install
      - name: R library
        run: ls -lt /usr/lib/R/library/

  exec:
    runs-on: ubuntu-latest
    needs: setup_and_install
    steps:
      - name: From CRAN
        run: sudo /usr/bin/R -e 'install.packages("dplyr", type = "binary", dependencies = TRUE)'
      - name: runner state and workspace check
        run: |
          ls -lt $GITHUB_WORKSPACE
          echo "R library:"
          ls -l /usr/lib/R/library/
          
          echo "R site-library:"
          ls -lt /usr/lib/R/site-library/
