# This is a basic workflow to help you get started with Actions

# NOTE:
# Further readings: https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+
#                   https://github.com/r-lib/actions
#                   https://pkgs.org/download/r-base-core

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ target ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #
      # Install R pkgs
      #
      - name: Add cran2deb4ubuntu 4.0 PPA
        run: sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
      - name: apt-get update & install aptitude
        run: |
          sudo apt-get update
          sudo apt-get install aptitude -y
      - name: apt-get upgrade
        run: sudo apt-get upgrade

      #sudo apt-get install --fix-broken --assume-yes r-base-core r-cran-dplyr r-cran-httr r-cran-jsonlite r-cran-readr r-cran-stringr r-cran-xml2 r-cran-whisker

      # rvest dependencies by binaries
      - name: rvest deps
        run: sudo aptitude install -f -y r-cran-dplyr r-cran-httr r-cran-jsonlite r-cran-selectr r-cran-xml2

      # Install r-vest
      - name: rvest packge install
        run: sudo /usr/bin/R -e 'install.packages("rvest")'
