#
# renv.cache.build.yml: build renv cache in GitHub environment
#

name: renv cache build
env:
  ARTIFACT_01: dummy.txt

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # JOB: RENV
  pre-cache:
    name: "Create/initialize re-usable R environment"
    # strict runner specification
    runs-on: ubuntu-20.04

    steps:


# renv ########################################################


      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: setup renv dependencies
        run: sudo apt install libssl-dev libcurl4-openssl-dev libxml2-dev

      - uses: r-lib/actions/setup-renv@v2

      #
      # Test R environment
      #
      #- name: rocker/tidyverse:4.1.2
      - name: R test
        run: |
          R --version
          Rscript -e 'renv::diagnostics()'

      - name: R session details
        run: Rscript -e 'sessionInfo()'

