name: SandBox
env:
  ARTIFACT_02: dataPatch.R.tgz
  ARTIFACT_03: renderWebPage.R.tgz

on:
  # This is an experimental workflow that is manually triggered
  workflow_dispatch:

jobs:
  clue:
    name: Download perturbagens from clue.io
    runs-on: ubuntu-latest
    
    steps:
      - name: "env dump"
        continue-on-error: true
        run: |
          env | sort
          echo ".... CPU DETAILS ........................."
          sudo lscpu
          sudo grep -E '^(processor|.+ id| cores|model|vendor|$|bugs|cpu|.+ size)' /proc/cpuinfo
          echo ".... OTHER SYSTEM DETAILS ........................."
          uname -a

  # experimental job to practice GHA features
  render:
    name: Render web representation of current dataset
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
    - name: "env dump"
      run: env | sort

    - uses: actions/checkout@v2

    - name: Get most recent "${{ env.ARTIFACT_02 }}" artifact
      run: |
        curl "https://api.github.com/repos/cycle20/scancer/actions/artifacts"
        bash -x src/get_artifact.bash "${{ secrets.GITHUB_TOKEN }}" "${{ env.ARTIFACT_02 }}"

    - name: "Extract ${{ env.ARTIFACT_02 }}"
      run: |
        echo "md5sum of cache file"
        md5sum ${{ env.ARTIFACT_02 }}
        mkdir -p OUTPUT
        tar --directory=OUTPUT -xzf ${{ env.ARTIFACT_02 }}

    - name: "Setup R dependencies"
      run: |
        sudo bash src/gh_action__setup_and_install.bash

    - name: Exec page rendering (renderWebPage.R)
      run: |
        Rscript R/renderWebPage.R
        ls -lt OUTPUT/*.html

    - name: "Wrap pages into '${{ env.ARTIFACT_03 }}'"
      run: tar --directory=OUTPUT -cvzf "${{ env.ARTIFACT_03 }}" index.target.*.html

    - name: "Upload artifact '${{ env.ARTIFACT_03 }}'"
      uses: actions/upload-artifact@v2.2.3
      with:
        name: "${{ env.ARTIFACT_03 }}"
        path: "${{ env.ARTIFACT_03 }}"
