name: SandBox
env:
  ARTIFACT_02: dataPatch.R.tgz
  UNIPROT_CACHE_DIR: G.D.CACHE

on:
  # This is an experimental workflow that is manually triggered
  workflow_dispatch:

jobs:
  clue:
    name: Download perturbagens from clue.io
    runs-on: ubuntu-latest
    
    steps:
      - name: "env dump"
        run: env | sort
    

  # experimental job to practice GHA features
  dataPatch:
    name: Collect missing data
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
    - name: "env dump"
      run: env | sort

    - uses: actions/checkout@v2

    - name: Get most recent "${{ env.ARTIFACT_02 }}" artifact
      run: |
        curl "https://api.github.com/repos/cycle20/scancer/actions/artifacts"
        bash -x src/get_artifact.bash "${{ secrets.GITHUB_TOKEN }}" "${{ env.ARTIFACT_02 }}"

    - name: "Drive task: download external UniProt cache stuff"
      run: |
        echo "Download cache stuff..."
        bash src/google_download.bash "${{ secrets.UNIPROT_PRE_CACHED }}" u.tgz
        echo "md5sum of cache file"
        md5sum u.tgz

    - name: tarball verbosed extraction of downloaded cache stuffs into ${{ env.UNIPROT_CACHE_DIR }}
      run: |
        mkdir -p "${{ env.UNIPROT_CACHE_DIR }}"
        tar --directory="${{ env.UNIPROT_CACHE_DIR }}" -xzf u.tgz
        
        mkdir -p OUTPUT
        tar --directory=OUTPUT -xzf ${{ env.ARTIFACT_02 }}

    - name: Snoop
      run: |
        pwd
        ls -ldt *
        find ~ -maxdepth 2 -type d

    - name: Merge UniProt cache into restored OUTPUT directory
      run: |
        UNI_CACHE="${{ env.UNIPROT_CACHE_DIR }}"
        GH_CACHE="OUTPUT/DATAPATH_CACHE"
        bash -x src/gh_action__merge_caches.bash
