name: SandBox
env:
  ARTIFACT_02: dataPatch.R.tgz
  ARTIFACT_03: renderWebPage.R.tgz

on:
  # This is an experimental workflow that is manually triggered
  workflow_dispatch:

jobs:
  checkout:
    name: Experiments with checkouts...
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: get artifact "${{ env.ARTIFACT_03 }}"
        run: |
          tree -d
          # get the script file
          curl -o get_artifact.bash  https://raw.githubusercontent.com/cycle20/scancer/main/src/get_artifact.bash
          # git checkout origin/main -- src/get_artifact.bash
          bash get_artifact.bash "${{ secrets.GITHUB_TOKEN }}" "${{ env.ARTIFACT_03 }}"
          # drop the script file (from the index as well)
          rm get_artifact.bash
          tree -d

      - name: gh-pages "deploy"
        run: |
          # auth
          # echo "${{secrets.GITHUB_TOKEN}}" | gh auth login --with-token
          # echo cat..........
          # cat .git/config

          git config  --local user.email "46718432+cycle20@users.noreply.github.com"
          git config  --local user.name cycle20

          mv PREV_RESULT/index.target.with.data.html .
          git add index.target.with.data.html
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          git commit -F <(\
            printf "Pushed by workflow: %s, run number: %d\n\n$RUN_URL" \
              "$GITHUB_WORKFLOW" \
              "$GITHUB_RUN_NUMBER" \
          )

          echo git push........................
          git push "https://${{ secrets.GH_PAGES_PAT }}@github.com/cycle20/scancer.git" \
            gh-pages:gh-pages2
          git pull
          git log -1
          git status

      # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
      - name: "env dump"
        run: |
          env | sort
