name: SandBox
env:
  ARTIFACT_02: dataPatch.R.tgz

on:
  # This is an experimental workflow that is manually triggered
  workflow_dispatch:

jobs:
  clue:
    name: Download perturbagens from clue.io
    runs-on: ubuntu-latest
    
    steps:
      - name: "env dump"
        run: env | sort
    

  # experimental job to practice GHA features
  dataPatch:
    name: Collect missing data
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
    - name: "env dump"
      run: env | sort

    - uses: actions/checkout@v2

    - name: Get most recent "${{ env.ARTIFACT_02 }}" artifact
      run: bash -x src/get_artifact.bash "${{ env.ARTIFACT_02 }}"

    - name: "Drive task: download external UniProt cache stuff"
      run: |
        echo "Download cache stuff..."
        bash src/google_download.bash "${{ secrets.UNIPROT_PRE_CACHED }}" u.tgz
        echo "md5sum of cache file"
        md5sum u.tgz

    - name: tarball verbosed extraction of downloaded cache stuffs
      run: |
        mkdir -p G.D.CACHE
        tar --directory=G.D.CACHE -xzf u.tgz
        
        mkdir -p OUTPUT
        tar --directory=OUTPUT -xzf ${{ env.ARTIFACT_02 }}

    - name: Snoop
      run: |
        pwd
        ls -ldt *
        find ~ -maxdepth 2 -type d

    - name: Merge UniProt cache into restored OUTPUT
      run: |
        CACHE="OUTPUT/DATAPATH_CACHE/cache.tsv"
        UNI_CACHE="UniProt_CacheLines.tsv"

        if [ -f "$CACHE" ]; then
          # exclude UniProt HTML lines
          echo "Merge cache files"
          {
            egrep -v 'https://www.uniprot.org/uniprot/[A-Z0-9]{6,10}\s' "$CACHE"
            egrep '\.html\s' "$UNI_CACHE"
          } > new_cache.tsv
          cp new_cache.tsv "$CACHE"
        else
          # just set it as starter cache file
          mkdir -p OUTPUT/DATAPATH_CACHE
          mv -v "$UNI_CACHE" "$CACHE"
        fi
