name: SandBox
env:
  ARTIFACT_02: dataPatch.R.tgz
  ARTIFACT_03: renderWebPage.R.tgz

on:
  # This is an experimental workflow that is manually triggered
  workflow_dispatch:

jobs:
  checkout:
    name: Experiments with checkouts...
    runs-on: ubuntu-latest

    steps:
      - name: get artifact "${{ env.ARTIFACT_03 }}"
        run: |
          bash src/get_artifact.bash "${{ secrets.GITHUB_TOKEN }}" "${{ env.ARTIFACT_03 }}"

      - name: gh-pages checkout
        run: |
          git clone https://github.com/cycle20/scancer.git \
            && cd scancer
          git checkout gh-pages
          git branch -a
          git log --oneline -10

          # auth
          # echo "${{secrets.GITHUB_TOKEN}}" | gh auth login --with-token
          # echo cat..........
          # cat .git/config

          git config  --local user.email "46718432+cycle20@users.noreply.github.com"
          git config  --local user.name cycle20

          echo "<!-- MINOR UPDATE -->" >> index.target.with.data.html

          git add index.target.with.data.html
          git commit -m "Test push from workflow"

          echo git push........................
          git push --verbose "https://${{ secrets.GH_PAGES_PAT }}@github.com/cycle20/scancer.git" gh-pages:gh-pages3
          git pull
          git status

      # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
      - name: "env dump"
        run: |
          env | sort
