#
# tests.yml: workflow file for running scancer tests
#

name: scancer tests

on:
  pull_request:
    branches: [ main ]

  # Allows manual start from the Actions tab
  workflow_dispatch:

jobs:

  tinytest:
    name: "Run tinytest tests"
    # strict runner specification
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: setup renv dependencies
        run: sudo apt install libssl-dev libcurl4-openssl-dev libxml2-dev

      - uses: r-lib/actions/setup-renv@v2

      #
      # Exec tinytest tests
      #
      - name: R test
        run: |
          R --version
          Rscript -e 'renv::diagnostics()'

      - name: R session details
        run: Rscript -e 'sessionInfo()'

      - name: Execute all tests
        run: Rscript -e 'tinytest::test_all()'

